version: '3'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "password"
      MONGODB_URI: "mongodb://localhost:27017"
  backend:
    build: ./backEnd
    ports:
      - "5000:5000"
  frontend:
    build: ./frontEnd
    ports:
      - "4200:4200"
